### ISSUE TITLE
[Core Concepts] Add Introduction to Cypress page - first part

### ISSUE THREAD

**Issue by pedrohyvo** [pedrohyvo/cypress-docs-pt-br#12]
Here are the sections that we need to covered when creating a PR to close this issue:

1. Cypress Can Be Simple (Sometimes)
2. Querying Elements

**Comment by brunopulis** [comment]
@pedrohyvo essa página é relativa a Introdução da sessão Core Concepts? Se sim, irei pegar ela.

**Comment by pedrohyvo** [comment]
@brunopulis this issue includes these sections:
- The header (the same what you'll learn in all pages)
- Cypress can be simple 
- Querying elements

I'll assign this PR to you, thanks for making your first contribution 🚀

**Comment by pedrohyvo** [comment]
@brunopulis Olá Pulis, tudo tranquilo?
Estamos mudando a estratégia para acompanhar melhor o progresso da tradução. Você poderia compartilhar como está o status?
A partir de agora tudo vai ser acompanhado nessa issue aqui - #22

**Comment by pedrohyvo** [comment]
O @brunopulis está sem tempo de trabalhar nessa issue agora, vou assinar pra ti e você pode continuar o trabalho na mesma página, pode ser?

**Comment by edmundobiglia** [comment]
@pedrohyvo pode ser sim, posso ficar com a página "Introduction to Cypress" inteira.

**Comment by pedrohyvo** [comment]
@edmundobiglia você pode seguir a mesma linha, traduz somente o que está no escopo dessa issue aqui e depois você vai pras outras. Aproveita e faz um comentário nas outras issues só pra ninguém pegar porque depois tudo vai ser rastreado na issue de tradução principal #22

**Comment by edmundobiglia** [comment]
@pedrohyvo Certo! Já comentei nas outras issues da página "Introduction to Cypress".

**Comment by pedrohyvo** [comment]
#53 is closed now
