### ISSUE TITLE
[Core Concepts] Add Introduction to Cypress page - Chains of Commands

### ISSUE THREAD

**Issue by pedrohyvo** [pedrohyvo/cypress-docs-pt-br#13]
Only `Chains of Commands` section needs to be covered when opening a PR to close this issue.

**Comment by edmundobiglia** [comment]
@pedrohyvo Hey there, I'd like to translate the **Chains of Commands** section.

**Comment by pedrohyvo** [comment]
@edmundobiglia thanks for contributing! Let me assign this issue to yourself and let me know if you need any help 😄

**Comment by edmundobiglia** [comment]
Thank you! Glad to help! :)

**Comment by pedrohyvo** [comment]
@edmundobiglia Olá Edmundo, tudo tranquilo? 
Estamos mudando a estratégia para acompanhar melhor o progresso da tradução. Você poderia compartilhar como está o status? 
A partir de agora tudo vai ser acompanhado nessa issue aqui - https://github.com/pedrohyvo/cypress-docs-pt-br/issues/22

**Comment by edmundobiglia** [comment]
@pedrohyvo Oi, Pedro, tudo bem? 
A seção "Chains of Commands" tem 3.100 palavras e eu traduzi 2.000, ou seja, cerca de 1/3. O que traduzi está agora está aqui:
https://github.com/edmundobiglia/cypress-docs-pt-br/blob/core-concepts-introduction-to-cypress/pages/core-concepts/introduction-to-cypress.md
Essa semana deu uma apertada aqui, mas termino a seção "Chains of Commands" até o fim de semana.

**Comment by pedrohyvo** [comment]
Tranquilo @edmundobiglia, top demais. 🚀
