### ISSUE TITLE
[Core Concepts] Add Introduction to Cypress page - Timeouts

### ISSUE THREAD

**Issue by pedrohyvo** [pedrohyvo/cypress-docs-pt-br#15]
Only `Timeouts` section needs to be covered in this PR.

**Comment by Ismael198** [comment]
Como trabalhar neste campo Pedro.

**Comment by edmundobiglia** [comment]
@pedrohyvo como estou com a página "Introduction to Cypress" inteira, vou ficar com esta seção também.

**Comment by pedrohyvo** [comment]
@edmundobiglia algum progresso nessa seção? Está precisando de ajuda?

**Comment by edmundobiglia** [comment]
@pedrohyvo desculpa, eu comecei num trabalho novo no mês passado, então tem estado bem corrido. Mas eu vou tirar um tempo pra terminar essa seção nesse fim de semana sem falta.

**Comment by pedrohyvo** [comment]
Página traduzida!
