### ISSUE TITLE
Traduzir a seção Contributing do README.md para PT-BR

### ISSUE THREAD

**Issue by wlsf82** [pedrohyvo/cypress-docs-pt-br#28]
No `README.md`, a seção **Contributing** está em Inglês, sendo que este é um repositório com a tradução da documentação de um repo para PT-BR, ou seja, a galera que vai contribuir com traduções devem falar português, portanto, faz mais sentido que esta seção esteja em PT-BR também.

**Comment by pedrohyvo** [comment]
@wlsf82 concordo, porém toda a estrutura e código deve ser mantida em inglês ex: commits, PR's
