### ISSUE TITLE
Adicionar disclaimer no repositório

### ISSUE THREAD

**Issue by brunopulis** [pedrohyvo/cypress-docs-pt-br#29]
Olá @pedrohyvo, 

Acho interessante colocar a [issue](https://github.com/cypress-io/cypress-documentation/issues/3084) onde o pessoal do Cypress comenta sobre o não suporte das outras traduções. 

Outro ponto interessante que estava pensando é deixar explícito que essa tradução não é oficial do framework, mas sim uma tradução feita pela comunidade. 

E precisando estamos ai.

**Comment by pedrohyvo** [comment]
@brunopulis excelente sugestão, vou adicionar essa seção, inclusive já estava com um rascunho dela ;)

**Comment by PauloGoncalvesBH** [comment]
Abri essa issue para entender como podemos tornar essa documentação acessível em docs.cypress.io: https://github.com/cypress-io/cypress-documentation/issues/3558
