### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by pedrohyvo** [pedrohyvo/cypress-docs-pt-br#4]
Here all items that need to be addressed on this issue:

- [x] About the project -
- [x] Badges - #24 #41
- [x] How to contribute - #21 #33
- [x] Disclaimer - #30
- [x] Contributors -
- [x] License - #38 #40

**Comment by wlsf82** [comment]
License is already added https://github.com/pedrohyvo/cypress-docs-pt-br/blob/master/LICENSE.

**Comment by pedrohyvo** [comment]
@all-contributors please add @pedrohyvo for infra and code

**Comment by pedrohyvo** [comment]
Closing this issue once we already have contributors section in README file
