### ISSUE TITLE
Add installing cypress section

### ISSUE THREAD

**Issue by pedrohyvo** [pedrohyvo/cypress-docs-pt-br#5]
Translate installing cypress page under getting started section from cypress official doc - https://docs.cypress.io/guides/getting-started/installing-cypress.html

**Comment by wlsf82** [comment]
Hi, @pedrohyvo! :wave:

Did you already share this repo on your networks to get more help on the translations?

**Comment by pedrohyvo** [comment]
> Hi, @pedrohyvo! 👋
> 
> Did you already share this repo on your networks to get more help on the translations?

My plan is to merge my opened PR and update all stuff related to contributing then I'll share on my LI network.
