### ISSUE TITLE
Setup Github actions and figure out a standard before merging

### ISSUE THREAD

**Issue by pedrohyvo** [pedrohyvo/cypress-docs-pt-br#7]
@wlsf82 I'd like to discuss what are the items we need to ensure if they are working well before pushing to master branch regarding to documentation repository. Any concerns?

**Comment by wlsf82** [comment]
> @wlsf82 I'd like to discuss what are the items we need to ensure if they are working well before pushing to the master branch regarding the documentation repository. Any concerns?

@pedrohyvo, since it's just markdown, maybe we could have a least this verification running on CI. Something like a markdown linting. See https://www.npmjs.com/package/markdownlint.

What do you think?

**Comment by pedrohyvo** [comment]
@wlsf82 cool! is there any other suggestion do you might have?

**Comment by wlsf82** [comment]
> @wlsf82 cool! is there any other suggestion do you might have?

No @pedrohyvo, I think this is a good start already.

**Comment by pedrohyvo** [comment]
For future reference: https://medium.com/@christinavhastenrath/github-actions-markdown-lint-setup-86d7f6ec934d
