### ISSUE TITLE
[Getting Started] Add Writing Your First Test page

### ISSUE THREAD

**Issue by pedrohyvo** [pedrohyvo/cypress-docs-pt-br#8]
Same as we did in #5

**Comment by lucastfa** [comment]
I can take this one.

**Comment by wlsf82** [comment]
> I can take this one.

@lucastfa, I've assigned it to you.

**Comment by lucastfa-toptal** [comment]
The page is huge so I will split it. This issue is related to Add a test file and Write your first test sections only.
